# trigger: apply source-based zero-alpha restoration v2
from pathlib import Path

path = Path('vite.tailwind-motion-cleanup.config.js')
text = path.read_text(encoding='utf-8')

old_sig = "const alphaPreservingSplitter = `async function splitIntoFifteen(blob) {"
new_sig = "const alphaPreservingSplitter = `async function splitIntoFifteen(blob, sourceFile = null) {"
if old_sig not in text:
    raise SystemExit('splitter signature anchor not found')
text = text.replace(old_sig, new_sig, 1)

anchor = """  const pixels = ctx.getImageData(0, 0, width, height).data;\n  const alphaAt = (x, y) => pixels[(y * width + x) * 4 + 3];\n\n"""
insert = """  const pixels = ctx.getImageData(0, 0, width, height).data;\n  const alphaAt = (x, y) => pixels[(y * width + x) * 4 + 3];\n\n  // Keep an aligned copy of the original uploaded sheet. The processed blob\n  // may already contain fully transparent (alpha 0) holes where a pale face,\n  // white outline or fine bright wisp was mistaken for background. Once alpha\n  // reaches 0 the processed PNG no longer carries usable RGB there, so the\n  // splitter must consult the original opaque source to recover those pixels.\n  let originalPixels = null;\n  let originalBackground = [0, 0, 0];\n  let originalHasDarkBorder = false;\n  if (sourceFile) {\n    try {\n      const original = await drawFileToCanvas(sourceFile);\n      const aligned = document.createElement('canvas');\n      aligned.width = width;\n      aligned.height = height;\n      const alignedCtx = aligned.getContext('2d', { willReadFrequently: true });\n      if (alignedCtx) {\n        alignedCtx.drawImage(\n          original.canvas,\n          0, 0, original.canvas.width, original.canvas.height,\n          0, 0, width, height\n        );\n        originalPixels = alignedCtx.getImageData(0, 0, width, height).data;\n\n        const border = [];\n        const step = Math.max(1, Math.floor(Math.min(width, height) / 420));\n        const addBorder = (x, y) => {\n          const p = (y * width + x) * 4;\n          border.push([originalPixels[p], originalPixels[p + 1], originalPixels[p + 2]]);\n        };\n        for (let x = 0; x < width; x += step) {\n          addBorder(x, 0);\n          addBorder(x, height - 1);\n        }\n        for (let y = step; y < height - 1; y += step) {\n          addBorder(0, y);\n          addBorder(width - 1, y);\n        }\n\n        const dark = border.filter(([r, g, b]) => {\n          const l = r * 0.2126 + g * 0.7152 + b * 0.0722;\n          return l <= 112 && Math.max(r, g, b) <= 148;\n        });\n        if (border.length && dark.length / border.length >= 0.55) {\n          originalHasDarkBorder = true;\n          for (const [r, g, b] of dark) {\n            originalBackground[0] += r;\n            originalBackground[1] += g;\n            originalBackground[2] += b;\n          }\n          originalBackground[0] /= dark.length;\n          originalBackground[1] /= dark.length;\n          originalBackground[2] /= dark.length;\n        }\n      }\n    } catch (sourceError) {\n      console.warn('Original-sheet alpha recovery unavailable:', sourceError);\n      originalPixels = null;\n    }\n  }\n\n"""
if anchor not in text:
    raise SystemExit('splitter pixel anchor not found')
text = text.replace(anchor, insert, 1)

old_loop = """          const sp = (sy * output.width + sx) * 4;\n          const sa = splitSource[sp + 3];\n          if (sa === 0 || sa === 255) continue;\n          const sr = splitSource[sp];\n          const sg = splitSource[sp + 1];\n          const sb = splitSource[sp + 2];\n          const sl = sr * 0.2126 + sg * 0.7152 + sb * 0.0722;\n"""
new_loop = """          const sp = (sy * output.width + sx) * 4;\n          const sa = splitSource[sp + 3];\n\n          // Zero-alpha recovery from the original opaque source. This is the\n          // critical case previous fixes could not repair: alpha 0 pixels have\n          // already lost their RGB in the processed PNG. Only enable this for\n          // sheets whose original border is demonstrably dark, so bright/white\n          // artwork can be restored without resurrecting a light background.\n          const sourceX = cropLeft + sx - safetyMargin;\n          const sourceY = cropTop + sy - safetyMargin;\n          const insideSource = originalPixels && sourceX >= cropLeft && sourceX < cropRight && sourceY >= cropTop && sourceY < cropBottom;\n          if (insideSource && originalHasDarkBorder) {\n            const op = (sourceY * width + sourceX) * 4;\n            const or = originalPixels[op];\n            const og = originalPixels[op + 1];\n            const ob = originalPixels[op + 2];\n            const ol = or * 0.2126 + og * 0.7152 + ob * 0.0722;\n            const bgDistance = Math.sqrt(\n              (or - originalBackground[0]) ** 2 +\n              (og - originalBackground[1]) ** 2 +\n              (ob - originalBackground[2]) ** 2\n            );\n\n            if (sa === 0 && ol >= 118 && bgDistance >= 72) {\n              splitData[sp] = or;\n              splitData[sp + 1] = og;\n              splitData[sp + 2] = ob;\n              splitData[sp + 3] = 255;\n              continue;\n            }\n\n            if (sa > 0 && sa < 255 && ol >= 118 && bgDistance >= 64) {\n              splitData[sp] = or;\n              splitData[sp + 1] = og;\n              splitData[sp + 2] = ob;\n              splitData[sp + 3] = 255;\n              continue;\n            }\n          }\n\n          if (sa === 0 || sa === 255) continue;\n          const sr = splitSource[sp];\n          const sg = splitSource[sp + 1];\n          const sb = splitSource[sp + 2];\n          const sl = sr * 0.2126 + sg * 0.7152 + sb * 0.0722;\n"""
if old_loop not in text:
    raise SystemExit('split repair loop anchor not found')
text = text.replace(old_loop, new_loop, 1)

transform_anchor = """      transformed = transformed.slice(0, splitStart)\n        + alphaPreservingSplitter\n        + transformed.slice(splitEnd)\n\n      const removeStart = transformed.indexOf('const removeBackground = async')\n"""
transform_insert = """      transformed = transformed.slice(0, splitStart)\n        + alphaPreservingSplitter\n        + transformed.slice(splitEnd)\n\n      const splitCallMarker = 'const items = await splitIntoFifteen(resultBlob);'\n      if (!transformed.includes(splitCallMarker)) {\n        throw new Error('[transparency-integrity] Auto-split invocation was not found')\n      }\n      transformed = transformed.replace(\n        splitCallMarker,\n        'const items = await splitIntoFifteen(resultBlob, file);'\n      )\n\n      const removeStart = transformed.indexOf('const removeBackground = async')\n"""
if transform_anchor not in text:
    raise SystemExit('split transform anchor not found')
text = text.replace(transform_anchor, transform_insert, 1)

path.write_text(text, encoding='utf-8')
print('Applied original-source zero-alpha restoration to auto split.')
