import { defineConfig } from 'vite'
import baseConfig from './vite.prompt-library-build.config.js'
import { phraseThemeExpansionV2 } from './vite.phrase-theme-plugin-v2.js'
import { phraseThemeExpansionV3 } from './vite.phrase-theme-plugin-v3.js'
import { photoReferencePromptStructure } from './vite.photo-reference-prompt-plugin.js'
import { goldenComboRebuildV2 } from './vite.golden-combo-plugin-v2.js'
import { adsensePlacementPlugin } from './vite.adsense-placement-plugin.js'
import { mainAdCleanupPlugin } from './vite.main-ad-cleanup-plugin.js'
import { bulkSaveLayoutPlugin } from './vite.bulk-save-layout-plugin.js'
import { defaultArtStyleFallbackPlugin } from './vite.default-art-style-fallback.js'
import { styleFiveAxisPresetsV2Plugin } from './vite.style-five-axis-presets-v2.js'
import { cute2DFullBodyVividLockPlugin } from './vite.cute-2d-fullbody-vivid-lock.js'
import { gptStyleDirectorLockPlugin } from './vite.gpt-style-director-lock.js'
import { modelPromptPriorityV4Plugin } from './vite.model-prompt-priority-v4.js'
import { grokStyleDirectorLockPlugin } from './vite.grok-style-director-lock.js'
import { geminiIdentityStyleLockPlugin } from './vite.gemini-identity-style-lock.js'
import { geminiLayoutInstanceLockPlugin } from './vite.gemini-layout-instance-lock.js'
import { geminiStyleSceneLockPlugin } from './vite.gemini-style-scene-lock.js'
import { geminiFinalExecutionLockPlugin } from './vite.gemini-final-execution-lock.js'
import { safeWhiteSheetRoutingPlugin } from './vite.safe-white-sheet-routing-plugin.js'
import { transparentSheetAspectPlugin } from './vite.transparent-sheet-aspect-plugin.js'
import { sceneTypographyDirectionV5Plugin } from './vite.scene-typography-direction-v5.js'
import { textContrastBackingLockV1Plugin } from './vite.text-contrast-backing-lock-v1.js'
import { styleFirstSemanticLockV3Plugin } from './vite.style-first-semantic-lock-v3.js'
import { slotIsolationLockPlugin } from './vite.slot-isolation-lock.js'
import { semanticPropDirectorV1Plugin } from './vite.semantic-prop-director-v1.js'
import { repairPromptV3Plugin } from './vite.repair-prompt-v3.js'

export default defineConfig({
  ...baseConfig,
  plugins: [repairPromptV3Plugin(), transparentSheetAspectPlugin(), safeWhiteSheetRoutingPlugin(), defaultArtStyleFallbackPlugin(), styleFiveAxisPresetsV2Plugin(), cute2DFullBodyVividLockPlugin(), gptStyleDirectorLockPlugin(), modelPromptPriorityV4Plugin(), grokStyleDirectorLockPlugin(), geminiIdentityStyleLockPlugin(), geminiLayoutInstanceLockPlugin(), geminiStyleSceneLockPlugin(), geminiFinalExecutionLockPlugin(), bulkSaveLayoutPlugin(), mainAdCleanupPlugin(), adsensePlacementPlugin(), photoReferencePromptStructure(), phraseThemeExpansionV2(), phraseThemeExpansionV3(), goldenComboRebuildV2(), slotIsolationLockPlugin(), semanticPropDirectorV1Plugin(), ...(baseConfig.plugins || []), sceneTypographyDirectionV5Plugin(), textContrastBackingLockV1Plugin(), styleFirstSemanticLockV3Plugin()],
})
